package es.fdi.iw.controller;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.DateFormat;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import java.util.UUID;

import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.io.IOUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;

import es.fdi.iw.ContextInitializer;
import es.fdi.iw.model.Author;
import es.fdi.iw.model.Book;
import es.fdi.iw.model.Genero;
import es.fdi.iw.model.User;
import es.fdi.iw.model.modificadores.ModificadorProduccion;
import es.fdi.iw.model.pais.Pais;
import es.fdi.iw.model.pais.Recursos;
import es.fdi.iw.model.pais.construcciones.Construcciones;
import es.fdi.iw.model.pais.TipoRecurso;
import es.fdi.iw.model.pais.eventos.Evento;
import es.fdi.iw.model.pais.eventos.TipoEvento;
import es.fdi.iw.model.politicos.ExceptionPolitico;
import es.fdi.iw.model.politicos.Politico;
import es.fdi.iw.model.usuario.ExceptionUsuario;
import es.fdi.iw.model.usuario.Rol;
import es.fdi.iw.model.usuario.TipoLider;
import es.fdi.iw.model.usuario.Usuario;
import es.fdi.iw.noticias.Noticia;

/**
 * Una aplicación de ejemplo para IW.
 */
@Controller
public class HomeController {

	private static final Logger logger = LoggerFactory.getLogger(HomeController.class);

	@PersistenceContext
	private EntityManager entityManager;

	/**
	 * Intercepts login requests generated by the header; then continues to load
	 * normal page
	 */
	@RequestMapping(value = "/login", method = RequestMethod.POST)
	@Transactional
	public String login(@RequestParam("login") String formLogin, @RequestParam("pass") String formPass,
			@RequestParam("source") String formSource, HttpServletRequest request, HttpServletResponse response,
			Model model, HttpSession session) {

		logger.info("Login attempt from '{}' while visiting '{}'", formLogin, formSource);

		// validate request
		if (formLogin == null || formLogin.length() < 4 || formPass == null || formPass.length() < 4) {
			model.addAttribute("loginError", "usuarios y contraseñas: 4 caracteres mínimo");
			response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
		} else {
			User u = null;
			try {
				u = (User) entityManager.createNamedQuery("userByLogin").setParameter("loginParam", formLogin)
						.getSingleResult();
				if (u.isPassValid(formPass)) {
					logger.info("pass was valid");
					session.setAttribute("user", u);
					// sets the anti-csrf token
					getTokenForSession(session);
				} else {
					logger.info("pass was NOT valid");
					model.addAttribute("loginError", "error en usuario o contraseña");
					response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
				}
			} catch (NoResultException nre) {
				if (formPass.length() == 4) {
					// UGLY: register new users if they do not exist and pass is
					// 4 chars long
					logger.info("no-such-user; creating user {}", formLogin);
					User user = User.createUser(formLogin, formPass, "user");
					entityManager.persist(user);
					session.setAttribute("user", user);
					// sets the anti-csrf token
					getTokenForSession(session);
				} else {
					logger.info("no such login: {}", formLogin);
				}
				model.addAttribute("loginError", "error en usuario o contraseña");
			}
		}

		// redirects to view from which login was requested
		return "redirect:" + formSource;
	}

	/**
	 * Delete a user; return JSON indicating success or failure
	 */
	@RequestMapping(value = "/delUser", method = RequestMethod.POST)
	@ResponseBody
	@Transactional // needed to allow DB change
	public ResponseEntity<String> bookAuthors(@RequestParam("id") long id, @RequestParam("csrf") String token,
			HttpSession session) {
		if (!isAdmin(session) || !isTokenValid(session, token)) {
			return new ResponseEntity<String>("Error: no such user or bad auth", HttpStatus.FORBIDDEN);
		} else if (entityManager.createNamedQuery("delUser").setParameter("idParam", id).executeUpdate() == 1) {
			return new ResponseEntity<String>("Ok: user " + id + " removed", HttpStatus.OK);
		} else {
			return new ResponseEntity<String>("Error: no such user", HttpStatus.BAD_REQUEST);
		}
	}

	/**
	 * Logout (also returns to home view).
	 */
	@RequestMapping(value = "/logout", method = RequestMethod.GET)
	public String logout(HttpSession session) {
		logger.info("User '{}' logged out", session.getAttribute("user"));
		session.invalidate();
		return "home2";
	}

	/**
	 * Uploads a photo for a user
	 * 
	 * @param id
	 *            of user
	 * @param photo
	 *            to upload
	 * @return
	 */
	@RequestMapping(value = "/user", method = RequestMethod.POST)
	public @ResponseBody String handleFileUpload(@RequestParam("photo") MultipartFile photo,
			@RequestParam("id") String id) {
		if (!photo.isEmpty()) {
			try {
				byte[] bytes = photo.getBytes();
				BufferedOutputStream stream = new BufferedOutputStream(
						new FileOutputStream(ContextInitializer.getFile("user", id)));
				stream.write(bytes);
				stream.close();
				return "You successfully uploaded " + id + " into "
						+ ContextInitializer.getFile("user", id).getAbsolutePath() + "!";
			} catch (Exception e) {
				return "You failed to upload " + id + " => " + e.getMessage();
			}
		} else {
			return "You failed to upload a photo for " + id + " because the file was empty.";
		}
	}

	/**
	 * Displays user details
	 */
	@RequestMapping(value = "/user", method = RequestMethod.GET)
	public String user(HttpSession session, HttpServletRequest request) {
		return "user";
	}

	/**
	 * Displays single-book details
	 */
	@RequestMapping(value = "/book/{id}", method = RequestMethod.GET)
	public String book(@PathVariable("id") long id, HttpServletResponse response, Model model) {
		Book b = entityManager.find(Book.class, id);
		if (b == null) {
			response.setStatus(HttpServletResponse.SC_NOT_FOUND);
			logger.error("No such book: {}", id);
		} else {
			model.addAttribute("book", b);
		}
		model.addAttribute("prefix", "../");
		return "book";
	}

	/**
	 * obtener los datos de la BD para modificar usuario
	 * 
	 * @param id
	 * @param response
	 * @param model
	 * @return
	 */
	@RequestMapping(value = "/modificarUsuario/{id}", method = RequestMethod.GET)
	public String usuario(@PathVariable("id") long id, HttpServletResponse response, Model model) {

		Usuario b = (Usuario) entityManager.createNamedQuery("usuarioById").setParameter("idParam", id)
				.getSingleResult();
		if (b == null) {
			response.setStatus(HttpServletResponse.SC_NOT_FOUND);
			logger.error("No such usuario: {}", id);
		} else {
			model.addAttribute("usuario", b);
			System.out.println(b.getId());

			model.addAttribute("prefix", "../"); // para generar URLs relativas
			return "modificarUsuario";
		}
		return "modificarUsuario";
	}

	/**
	 * obtener los datos de la BD para modificar politico
	 * 
	 * @param id
	 * @param response
	 * @param model
	 * @return
	 */
	@RequestMapping(value = "/modificarPolitico/{id}", method = RequestMethod.GET)
	public String politico(@PathVariable("id") long id, HttpServletResponse response, Model model) {

		Politico b = (Politico) entityManager.createNamedQuery("politicoById").setParameter("idParam", id)
				.getSingleResult();
		if (b == null) {
			response.setStatus(HttpServletResponse.SC_NOT_FOUND);
			logger.error("No such usuario: {}", id);
		} else {
			model.addAttribute("politico", b);

			model.addAttribute("prefix", "../"); // para generar URLs relativas
			return "modificarPolitico";
		}
		return "modificarPolitico";
	}

	/**
	 * Delete a book
	 */
	@RequestMapping(value = "/book/{id}", method = RequestMethod.DELETE)
	@Transactional
	@ResponseBody
	public String rmbook(@PathVariable("id") long id, HttpServletResponse response, Model model) {
		try {
			Book b = entityManager.find(Book.class, id);
			for (Author a : b.getAuthors()) {
				a.getWritings().remove(b);
				entityManager.persist(a);
			}
			entityManager.remove(b);
			response.setStatus(HttpServletResponse.SC_OK);
			return "OK";
		} catch (NoResultException nre) {
			logger.error("No such book: {}", id, nre);
			response.setStatus(HttpServletResponse.SC_NOT_FOUND);
			return "ERR";
		}
	}

	/*
	 * List all books
	 */
	@RequestMapping(value = "/books", method = RequestMethod.GET)
	@Transactional
	public String books(Model model) {
		model.addAttribute("books", entityManager.createNamedQuery("allBooks").getResultList());
		model.addAttribute("owners", entityManager.createNamedQuery("allUsers").getResultList());
		model.addAttribute("authors", entityManager.createNamedQuery("allAuthors").getResultList());
		return "books";
	}

	/*
	 * Add a book
	 */
	@RequestMapping(value = "/book", method = RequestMethod.POST)
	@Transactional
	public String book(@RequestParam("owner") long ownerId, @RequestParam("authors") long[] authorIds,
			@RequestParam("title") String title, @RequestParam("description") String description, Model model) {
		Book b = new Book();
		b.setTitle(title);
		b.setDescription(description);
		for (long aid : authorIds) {
			// adding authors to book is useless, since author is the owning
			// side (= has no mappedBy)
			Author a = entityManager.find(Author.class, aid);
			a.getWritings().add(b);
			entityManager.persist(a);
		}
		b.setOwner(entityManager.getReference(User.class, ownerId));
		entityManager.persist(b);
		entityManager.flush();
		logger.info("Book " + b.getId() + " written ok - owned by " + b.getOwner().getLogin() + " written by "
				+ b.getAuthors());

		return "redirect:book/" + b.getId();
	}

	/**
	 * Load book authors for a given book via post; return as JSON
	 */
	@RequestMapping(value = "/bookAuthors")
	@ResponseBody
	@Transactional // needed to allow lazy init to work
	public ResponseEntity<String> bookAuthors(@RequestParam("id") long id, HttpServletRequest request) {
		try {
			Book book = (Book) entityManager.find(Book.class, id);
			List<Author> authors = book.getAuthors();
			StringBuilder sb = new StringBuilder("[");
			for (Author a : authors) {
				if (sb.length() > 1)
					sb.append(",");
				sb.append("{ " + "\"id\": \"" + a.getId() + "\", " + "\"familyName\": \"" + a.getFamilyName() + "\", "
						+ "\"lastName\": \"" + a.getLastName() + "\"}");
			}
			return new ResponseEntity<String>(sb + "]", HttpStatus.OK);
		} catch (NoResultException nre) {
			logger.error("No such book: {}", id, nre);
		}
		return new ResponseEntity<String>("Error: libro no existe", HttpStatus.BAD_REQUEST);
	}

	/**
	 * Displays author details
	 */
	@RequestMapping(value = "/author/{id}", method = RequestMethod.GET)
	public String author(@PathVariable("id") long id, Model model) {
		try {
			model.addAttribute("author", entityManager.find(Author.class, id));
		} catch (NoResultException nre) {
			logger.error("No such author: {}", id, nre);
		}
		model.addAttribute("prefix", "../");
		return "author";
	}

	/**
	 * Returns a users' photo
	 * 
	 * @param id
	 *            id of user to get photo from
	 * @return
	 */
	@ResponseBody
	@RequestMapping(value = "/user/photo", method = RequestMethod.GET, produces = MediaType.IMAGE_JPEG_VALUE)
	public byte[] userPhoto(@RequestParam("id") String id) throws IOException {
		File f = ContextInitializer.getFile("user", id);
		InputStream in = null;
		if (f.exists()) {
			in = new BufferedInputStream(new FileInputStream(f));
		} else {
			in = new BufferedInputStream(this.getClass().getClassLoader().getResourceAsStream("unknown-user.jpg"));
		}

		return IOUtils.toByteArray(in);
	}

	/**
	 * Toggles debug mode
	 */
	@RequestMapping(value = "/debug", method = RequestMethod.GET)
	public String debug(HttpSession session, HttpServletRequest request) {
		String formDebug = request.getParameter("debug");
		logger.info("Setting debug to {}", formDebug);
		session.setAttribute("debug", "true".equals(formDebug) ? "true" : "false");
		return "redirect:/";
	}

	@RequestMapping(value = "/s", method = RequestMethod.GET)
	public String poniendoSesion(Locale locale, Model model, HttpSession session) {
		// session.setAttribute("user", "juan");
		return "home";
	}

	@RequestMapping(value = "/vistaAdminEditor", method = RequestMethod.GET)
	public String vistaAdminEditor(Locale locale, Model model, HttpSession session) {
		model.addAttribute("editores",
				entityManager.createNamedQuery("allUsuarioRol").setParameter("rolParam", Rol.Editor).getResultList());
		return "vistaAdminEditor";
	}

	@RequestMapping(value = "/vistaAdminUsuario", method = RequestMethod.GET)
	public String vistaAdminUsuario(Locale locale, Model model, HttpSession session) {
		model.addAttribute("usuarios", entityManager.createNamedQuery("allUsuarioRol")
				.setParameter("rolParam", Rol.UsuarioRegistrado).getResultList());
		return "vistaAdminUsuario";
	}

	@RequestMapping(value = "/vistaAdminNoticias", method = RequestMethod.GET)
	public String vistaAdminNoticias(Locale locale, Model model, HttpSession session) {
		// model.addAttribute("admin", "pedro");
		return "vistaAdminNoticias";
	}

	@RequestMapping(value = "/vistaAdminEventos", method = RequestMethod.GET)
	public String vistaAdminEventos(Model model, HttpSession session) {
		model.addAttribute("eventos", entityManager.createNamedQuery("allEventos").getResultList());
		return "vistaAdminEventos";
	}

	@RequestMapping(value = "/crearEvento", method = RequestMethod.GET)
	public String crearEvento(Locale locale, Model model, HttpSession session) {

		return "crearEvento";
	}

	@RequestMapping(value = "/crearEven", method = RequestMethod.POST)
	@Transactional
	public String nuevoEvento(@RequestParam("nombreEvento") String formNombreEvento,
			@RequestParam("tipo") String formTipo, @RequestParam("descripcion") String formDrecripcion,
			@RequestParam("nombreOpcion1") String formNombreOpcion1, @RequestParam("tipoRecurso1") String formRecurso1,
			@RequestParam("modificador1") String formModificador1,
			@RequestParam("nombreOpcion2") String formNombreOpcion2, @RequestParam("tipoRecurso2") String formRecurso2,
			@RequestParam("modificador2") String formModificador2,
			@RequestParam("fechaActivacion") String formFechaActivacion, HttpServletRequest request,
			HttpServletResponse response, Model model, HttpSession session) throws ParseException, IOException {

		int modificador1 = Integer.parseInt(formModificador1);
		int modificador2 = Integer.parseInt(formModificador2);

		SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
		Date fechajava = null;
		try {
			fechajava = formato.parse(formFechaActivacion);
		} catch (ParseException ex) {
			System.out.println(ex);
		}
		java.sql.Date fecha = new java.sql.Date(fechajava.getTime());

		TipoRecurso recurso1 = TipoRecurso.stringtoRecurso(formRecurso1);
		TipoRecurso recurso2 = TipoRecurso.stringtoRecurso(formRecurso2);
		TipoEvento evento = TipoEvento.stringtoEvento(formTipo);

		System.out.println(formNombreEvento);
		System.out.println(evento);
		System.out.println(formDrecripcion);
		System.out.println(formNombreOpcion1);
		System.out.println(recurso1);
		System.out.println(modificador1);
		System.out.println(formNombreOpcion2);
		System.out.println(recurso2);
		System.out.println(modificador2);
		System.out.println(fecha);

		try {
			/*
			 * (String tit, String desc, String opt1, String opt2, TipoRecurso
			 * tipRec1, TipoRecurso tipRec2, int porcent1, int porcent2,
			 * TipoEvento tipo, Date fecha)
			 */
			Evento e = new Evento(formNombreEvento, formDrecripcion, formNombreOpcion1, formNombreOpcion2, recurso1,
					recurso2, modificador1, modificador2, evento, fecha);
			System.out.println(e.getTitulo());
			entityManager.persist(e);
			entityManager.flush();
			return "redirect:" + "vistaAdminEventos";

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return "redirect:" + "vistaAdminEventos";
	}

	@RequestMapping(value = "/even/{id}", method = RequestMethod.DELETE)
	@Transactional
	@ResponseBody
	public String rmEven(@PathVariable("id") long id, HttpServletResponse response, Model model) {
		try {
			Evento e = entityManager.find(Evento.class, id);
			entityManager.remove(e);
			response.setStatus(HttpServletResponse.SC_OK);

			return "OK";
		} catch (NoResultException nre) {
			logger.error("No existe ese evento: {}", id, nre);
			response.setStatus(HttpServletResponse.SC_NOT_FOUND);

			return "ERR";
		}
	}

	/**
	 * 
	 * Devolver todos los políticos de la BD
	 * 
	 * @param model
	 * @param session
	 * @return
	 */
	@RequestMapping(value = "/vistaAdminPoliticos", method = RequestMethod.GET)
	public String vistaAdminPoliticos(Model model, HttpSession session) {

		model.addAttribute("politicos", entityManager.createNamedQuery("allPoliticos").getResultList());

		return "vistaAdminPoliticos";
	}

	@RequestMapping(value = "/w", method = RequestMethod.GET)
	public String poniendoModelo(Locale locale, Model model, HttpSession session) {
		// model.addAttribute("anterior", session.getAttribute("user"));
		model.addAttribute("user", "pedro");
		return "home2";
	}

	@RequestMapping(value = "/pru", method = RequestMethod.GET)
	public String prueba2(Locale locale, Model model, HttpSession session) {
		// model.addAttribute("anterior", session.getAttribute("user"));
		model.addAttribute("test", "pedro");
		return "home2";
	}

	@RequestMapping(value = "/o", method = RequestMethod.GET)
	public String logout(Locale locale, Model model, HttpSession session) {
		return "home2";
	}

	public String algo(Locale locale, Model model, HttpSession session) {
		return "redirect:logout";
	}

	/**
	 * Simply selects the home view to render by returning its name.
	 */
	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String empty(Locale locale, Model model) {
		logger.info("Welcome home! The client locale is {}.", locale);

		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, locale);

		String formattedDate = dateFormat.format(date);

		model.addAttribute("serverTime", formattedDate);
		model.addAttribute("pageTitle", "BePolitics");

		return "home2";
	}

	/**
	 * Simply selects the home view to render by returning its name.
	 */
	@RequestMapping(value = "/home", method = RequestMethod.GET)
	public String index(Locale locale, Model model) {
		return empty(locale, model);
	}

	/**
	 * A not-very-dynamic view that shows an "about us".
	 */
	@RequestMapping(value = "/about", method = RequestMethod.GET)
	@Transactional
	public String about(Locale locale, Model model) {
		logger.info("User is looking up 'about us'");
		@SuppressWarnings("unchecked")
		List<User> us = (List<User>) entityManager.createQuery("select u from User u").getResultList();
		System.err.println(us.size());
		model.addAttribute("users", us);
		model.addAttribute("pageTitle", "IW: Quienes somos");
		return "about";
	}

	/**
	 * Checks the anti-csrf token for a session against a value
	 * 
	 * @param session
	 * @param token
	 * @return the token
	 */
	static boolean isTokenValid(HttpSession session, String token) {
		Object t = session.getAttribute("csrf_token");
		return (t != null) && t.equals(token);
	}

	/**
	 * Returns an anti-csrf token for a session, and stores it in the session
	 * 
	 * @param session
	 * @return
	 */
	static String getTokenForSession(HttpSession session) {
		String token = UUID.randomUUID().toString();
		session.setAttribute("csrf_token", token);
		return token;
	}

	/**
	 * Returns true if the user is logged in and is an admin
	 */
	static boolean isAdmin(HttpSession session) {
		User u = (User) session.getAttribute("user");
		if (u != null) {
			return u.getRole().equals("admin");
		} else {
			return false;
		}
	}

	/**
	 * Returns true if the user is logged in and is an admin
	 */
	static boolean esAdministrador(HttpSession session) {
		Usuario u = (Usuario) session.getAttribute("rol");
		if (u != null) {
			return u.getRol().toString().equals(Rol.Administrador.toString());
		} else {
			return false;
		}
	}

	/**
	 * Lleva a la pag de login
	 */
	@RequestMapping(value = "/iniciarSesion", method = RequestMethod.GET)
	@Transactional
	public String iniciarsesion(Locale locale, Model model) {

		model.addAttribute("pageTitle", "Iniciar Sesión");
		return "iniciarSesion";
	}

	// TODO crear el pais despues de crear al usuario

	@RequestMapping(value = "/crearUsuario", method = RequestMethod.POST)
	@Transactional
	public String nuevaCuenta(@RequestParam("nombre") String formNombre,
			@RequestParam("apellidos") String formApellidos, @RequestParam("correo") String formCorreo,
			@RequestParam("genero") String formGenero, @RequestParam("edad") String formEdad,
			@RequestParam("nick") String formNick, @RequestParam("contra") String formContra,
			@RequestParam("pais") String formPais, @RequestParam("lider") String formLider,
			@RequestParam("rol") String formRol, @RequestParam("source") String formSource,

			HttpServletRequest request, HttpServletResponse response, Model model, HttpSession session) {

		Pais p = null;
		if (formRol.isEmpty()) {
			formRol = "UsuarioRegistrado";
		}

		int edad = Integer.parseInt(formEdad);
		Usuario u = null;

		boolean isLoggedIn = session.getAttribute("rol") != null;

		try {
			formRol = formRol.toLowerCase();
			if (formRol.equals("administrador") || formRol.equals("editor")) {
				// agujero gordo si !isAdmin pero especifica rol admin

				// TODO BORRAR
				/*
				 * Construcciones c= new Construcciones(" ");
				 * entityManager.persist(c); Recursos re = new Recursos();
				 * entityManager.persist(re); p = new Pais(c,formPais,re);
				 * entityManager.persist(p);
				 * 
				 */

				Rol r = formRol.equals("editor") ? Rol.Editor : Rol.Administrador;
				u = new Usuario(formNombre, formApellidos, formCorreo, Genero.valueOf(formGenero), edad, formNick, null,
						TipoLider.valueOf(formLider), formContra, r);
			} else {

				Construcciones c = new Construcciones(" ");
				entityManager.persist(c);
				Recursos r = new Recursos();
				entityManager.persist(r);
				p = new Pais(c, formPais, r);
				entityManager.persist(p);
				u = new Usuario(formNombre, formApellidos, formCorreo, Genero.valueOf(formGenero), edad, formNick, p,
						TipoLider.valueOf(formLider), formContra, Rol.Administrador);
			}

			entityManager.persist(u);
			// entityManager.flush(); // <- implicito al final de la transaccion

			String rol = u.getRol().toString();
			System.out.println(rol);
			if (!esAdministrador(session)) {
				session.setAttribute("rol", u);
				getTokenForSession(session);
			} else {
				// String formSource = request.getParameter("formSource");
				return "redirect:" + formSource;
			}

		} catch (ExceptionUsuario e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return "home2";

	}

	@RequestMapping(value = "/entrar", method = RequestMethod.POST)
	@Transactional
	public String nuevaSesion(@RequestParam("nick") String formNick, @RequestParam("contra") String formContra,
			@RequestParam("source") String formSource, HttpServletRequest request, HttpServletResponse response,
			Model model, HttpSession session) {

		logger.info("Login attempt from '{}' while visiting '{}'", formNick, formSource);

		// validate request
		if (formNick == null || formContra == null || formContra.length() < 6) {
			model.addAttribute("loginError", "Rellene el campo Nick \n Contraseña : 6 caracteres mínimo");
			response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
		} else {
			System.out.println(formNick);
			Usuario u = new Usuario();
			// http://alejandroayala.solmedia.ec/?p=947 (Para que sirve el try
			// catch)
			try {
				u = (Usuario) entityManager.createNamedQuery("usuarioByLogin").setParameter("loginParam", formNick)
						.getSingleResult();
				System.out.println(u.getNick());
			} catch (NoResultException nre) {
			}
			return "home2";
		}
		return "home2";
	}

	@RequestMapping(value = "/eventosEditor", method = RequestMethod.GET)
	public String eventosEditor(Locale locale, Model model, HttpSession session) {
		// session.setAttribute("user", "juan");
		session.setAttribute("test", "pedro");
		return "eventosEditor";
	}

	@RequestMapping(value = "/crearCuenta", method = RequestMethod.GET)
	public String crearCuenta(Locale locale, Model model, HttpSession session) {
		return "crearCuenta";
	}

	@RequestMapping(value = "/eventos", method = RequestMethod.GET)
	public String eventos(Locale locale, Model model, HttpSession session) {
		// session.setAttribute("user", "juan");
		session.setAttribute("user", "pedro");
		return "eventos";
	}

	@RequestMapping(value = "/guerras", method = RequestMethod.GET)
	public String guerras(Locale locale, Model model, HttpSession session) {
		// session.setAttribute("user", "juan");
		session.setAttribute("user", "pedro");
		return "guerras";
	}

	@RequestMapping(value = "/produccion", method = RequestMethod.GET)
	public String produccion(Locale locale, Model model, HttpSession session) {
		// session.setAttribute("user", "juan");
		session.setAttribute("user", "pedro");
		return "produccion";
	}

	@RequestMapping(value = "/ministerios", method = RequestMethod.GET)
	public String ministerios(Locale locale, Model model, HttpSession session) {
		// session.setAttribute("user", "juan");
		session.setAttribute("user", "pedro");
		return "ministerios";
	}

	@RequestMapping(value = "/cupulaDeGobierno", method = RequestMethod.GET)
	public String cupulaDeGobierno(Locale locale, Model model, HttpSession session) {
		// session.setAttribute("user", "juan");
		session.setAttribute("user", "pedro");
		return "cupulaDeGobierno";
	}

	@RequestMapping(value = "/mercado", method = RequestMethod.GET)
	public String mercado(Locale locale, Model model, HttpSession session) {
		// session.setAttribute("user", "juan");
		session.setAttribute("user", "pedro");
		return "mercado";
	}

	@RequestMapping(value = "/alianzas", method = RequestMethod.GET)
	public String alianzas(Locale locale, Model model, HttpSession session) {

		session.setAttribute("user", "pedro");// session.setAttribute("user",
												// "juan");
		return "alianzas";
	}

	/**
	 * Devolver todos los politicos mostrandolos de mejor político a peor, es
	 * decir, politico con mejores estadísticas el primero
	 * 
	 * @param locale
	 * @param model
	 * @param session
	 * @return
	 */
	@RequestMapping(value = "/ranking", method = RequestMethod.GET)
	public String ranking(Locale locale, Model model, HttpSession session) {
		model.addAttribute("politicos", entityManager.createNamedQuery("allPoliticos").getResultList());
		return "ranking";
	}

	@RequestMapping(value = "/noticias", method = RequestMethod.GET)

	public String noticias(Locale locale, Model model, HttpSession session) {
		session.setAttribute("user", "pedro");
		// model.addAttribute("anterior", session.getAttribute("user"));
		return "noticias";
	}

	@RequestMapping(value = "/crearPolitico", method = RequestMethod.GET)
	public String crearPolitico(Locale locale, Model model, HttpSession session) {
		return "crearPolitico";
	}

	@RequestMapping(value = "/modificarUsuario", method = RequestMethod.GET)
	public String modificarUsuario(Locale locale, Model model, HttpSession session) {
		return "redirect: modificarUsuario";
	}

	@RequestMapping(value = "/modificarPolitico", method = RequestMethod.GET)
	public String modificarPol(Locale locale, Model model, HttpSession session) {
		return "modificarPolitico";
	}

	@RequestMapping(value = "/crearPol", method = RequestMethod.POST)
	@Transactional
	public String nuevoPolitico(@RequestParam("nombre") String formNombre, @RequestParam("cita") String formCita,
			@RequestParam("honestidad") String formHonestidad, @RequestParam("carisma") String formCarisma,
			@RequestParam("elocuencia") String formElocuencia, @RequestParam("popularidad") String formPopularidad,
			HttpServletRequest request, HttpServletResponse response, Model model, HttpSession session)
					throws ExceptionPolitico {

		int honestidad = Integer.parseInt(formHonestidad);
		int carisma = Integer.parseInt(formCarisma);
		int elocuencia = Integer.parseInt(formElocuencia);
		int popularidad = Integer.parseInt(formPopularidad);
		System.out.println(honestidad);
		System.out.println(carisma);
		System.out.println(elocuencia);
		System.out.println(popularidad);
		Pais pais = null;

		try {
			Politico p = new Politico(carisma, elocuencia, honestidad, formNombre, popularidad, formCita, pais);
			entityManager.persist(p);
			entityManager.flush();
			return "redirect:" + "vistaAdminPoliticos";

		} catch (ExceptionPolitico e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return "redirect:" + "vistaAdminPoliticos";

	}

	@RequestMapping(value = "/modificarPol", method = RequestMethod.POST)
	@Transactional
	public String modificarPol(@RequestParam("nombre") String formNombre, @RequestParam("cita") String formCita,
			@RequestParam("honestidad") String formHonestidad, @RequestParam("carisma") String formCarisma,
			@RequestParam("elocuencia") String formElocuencia, @RequestParam("popularidad") String formPopularidad,
			@RequestParam("source") String formId, HttpServletRequest request, HttpServletResponse response,
			Model model, HttpSession session) throws ExceptionPolitico {

		int honestidad = Integer.parseInt(formHonestidad);
		int carisma = Integer.parseInt(formCarisma);
		int elocuencia = Integer.parseInt(formElocuencia);
		int popularidad = Integer.parseInt(formPopularidad);
		Long id = Long.parseLong(formId);

		Politico p = entityManager.find(Politico.class, id);

		if (formCarisma != null) {
			p.setCarisma(carisma);
		}
		if (formHonestidad != null) {
			p.setHonestidad(honestidad);
		}
		if (formElocuencia != null) {
			p.setElocuencia(elocuencia);
		}
		if (formPopularidad != null) {
			p.setPopularidad(popularidad);
		}
		if (formNombre != null) {
			p.setNombre(formNombre);
		}
		if (formCita != null) {
			p.setCita(formCita);
		}

		p.setSumaStats(p.getCarisma() + p.getHonestidad() + p.getElocuencia() + p.getPopularidad());

		System.out.println(p.getSumaStats());
		entityManager.merge(p);

		entityManager.flush();
		return "redirect:" + "vistaAdminPoliticos";

	}

	// TODO crear el pais despues de crear al usuario CONTINUAR

	@RequestMapping(value = "/modificarUsu", method = RequestMethod.POST)
    @Transactional
    public String modificarUsu(
                    @RequestParam("nombre") String formNombre,
                    @RequestParam("apellidos") String formApellidos,
                    @RequestParam("correo") String formCorreo,
                    @RequestParam("genero") String formGenero,
                    @RequestParam("edad") String formEdad,
                    @RequestParam("nick") String formNick,
                    @RequestParam("contra") String formContra,
                    @RequestParam("pais") String formPais,
                    @RequestParam("lider") String formLider,
                    @RequestParam("id") String formId,
                    HttpServletRequest request, HttpServletResponse response, 
                    Model model, HttpSession session){
    
                    Long id = Long.parseLong(formId);
                    int edad = Integer.parseInt(formEdad);
                    
                    
                    
                    Usuario u = entityManager.find(Usuario.class, id);
                    if(u.getRol() == Rol.UsuarioRegistrado){
            
                            Pais p = u.getPais();
                            p = entityManager.find(Pais.class,p.getId());
                            
                            if(formPais != ""){
                                    p.setComunidad(p.getComunidad());
                                    p.setConstrucciones(p.getConstrucciones());
                                    p.setGuerra(p.getGuerra());
                                    p.setId(p.getId());
                                    p.setLastProduction(p.getLastProduction());
                                    p.setModificadores(p.getModificadores());
                                    p.setPoliticos(p.getPoliticos());
                                    p.setRecursos(p.getRecursos());
                                    p.setNombre(formPais);
                                    u.setPais(p);
                            }
                    }

                    if (formApellidos != "") {
                            u.setApellidos(formApellidos);
                    }
                    if (formNombre != "") {
                            u.setNombre(formNombre);
                    }
                    if (formGenero != null) {
                            u.setGenero(Genero.valueOf(formGenero));
                    }
                    if (formCorreo != "") {
                            u.setEmail(formCorreo);
                    }
                    if (formNick != "") {
                            u.setNick(formNick);
                    }
                    if (formContra != "") {
                            u.setHashedAndSalted(formContra);
                    }
                    if (formLider != "") {
                            u.settipoLider(TipoLider.valueOf(formLider));
                    }
                    if (formEdad != "") {
                            u.setEdad(edad);
                    }
               
                    entityManager.merge(u);          
                    entityManager.flush();
                    
                    if(u.getRol() == Rol.Editor){
                            return "redirect: vistaAdminEditor" ;
                    }
                    else if(u.getRol() == Rol.UsuarioRegistrado){
                            return "redirect: vistaAdminUsuario" ;
                    }
                    return "home2";         
    }

	/**
	 * Inicio sesion Admin
	 */
	@RequestMapping(value = "/vistaAdmin", method = RequestMethod.GET)
	public String vistaAdmin(Locale locale, Model model, HttpSession session) {
		model.addAttribute("anterior", session.getAttribute("user"));
		model.addAttribute("admin", "pedro");
		return "home2";
	}

	/**
	 * Inicio sesion Editor
	 */
	@RequestMapping(value = "/vistaEditor", method = RequestMethod.GET)
	public String vistaEditor(Locale locale, Model model, HttpSession session) {
		// model.addAttribute("anterior", session.getAttribute("user"));
		model.addAttribute("test", "pedro");
		return "home2";
	}

	/**
	 * Inicio sesion Jugador
	 */
	@RequestMapping(value = "/vistaJugador", method = RequestMethod.GET)
	public String vistaJugador(Locale locale, Model model, HttpSession session) {
		// model.addAttribute("anterior", session.getAttribute("user"));
		model.addAttribute("user", "pedro");
		return "home2";
	}

	@RequestMapping(value = "/poli/{id}", method = RequestMethod.DELETE)
	@Transactional
	@ResponseBody
	public String rmPoli(@PathVariable("id") long id, HttpServletResponse response, Model model) {
		try {
			Politico b = entityManager.find(Politico.class, id);
			entityManager.remove(b);
			b = null;
			response.setStatus(HttpServletResponse.SC_OK);
			return "OK";
		} catch (NoResultException nre) {
			logger.error("No existe ese politico: {}", id, nre);
			response.setStatus(HttpServletResponse.SC_NOT_FOUND);

			return "ERR";
		}
	}

	@RequestMapping(value = "/editor/{id}", method = RequestMethod.DELETE)
	@Transactional
	@ResponseBody
	public String rmEditor(@PathVariable("id") long id, HttpServletResponse response, Model model) {
		try {
			Usuario b = entityManager.find(Usuario.class, id);
			entityManager.remove(b);
			b = null;
			response.setStatus(HttpServletResponse.SC_OK);
			return "OK";
		} catch (NoResultException nre) {
			logger.error("No existe ese politico: {}", id, nre);
			response.setStatus(HttpServletResponse.SC_NOT_FOUND);

			return "ERR";
		}
	}

	@RequestMapping(value = "/usuario/{id}", method = RequestMethod.DELETE)
	@Transactional
	@ResponseBody
	public String rmUsuario(@PathVariable("id") long id, HttpServletResponse response, Model model) {
		try {
			Usuario b = entityManager.find(Usuario.class, id);
			entityManager.remove(b);
			b = null;
			response.setStatus(HttpServletResponse.SC_OK);
			return "OK";
		} catch (NoResultException nre) {
			logger.error("No existe ese politico: {}", id, nre);
			response.setStatus(HttpServletResponse.SC_NOT_FOUND);

			return "ERR";
		}
	}

	/**************************************************************/
	/************************** NOTICIAS **************************/
	/**************************************************************/

	/**
	 * Crea una noticia
	 */
	@RequestMapping(value = "/crearNoticia", method = RequestMethod.POST)
	@Transactional
	public String crearNoticia(@RequestParam("source") String formSource, @RequestParam("titulo") String formTitulo,
			@RequestParam("cuerpo") String formCuerpo, Model model, HttpSession session, HttpServletRequest request,
			HttpServletResponse response) {

		Noticia n = new Noticia(formTitulo, formCuerpo);

		if (n.getTitulo() != null && n.getTitulo().length() > 3 && n.getCuerpo() != null
				&& n.getCuerpo().length() > 10) {
			logger.info("\nInsertada noticia con título: " + n.getTitulo() + "\nY texto: " + n.getCuerpo() + "\n");
			entityManager.persist(n);
			// entityManager.flush();
		} else {
			logger.info("\nFallo al añadir noticia, titulo: " + n.getTitulo() + "\ncuerpo: " + n.getCuerpo() + "\n");
		}
		return "redirect:" + formSource;
	}

	/**
	 * Hace una lista de todas las noticias
	 */
	@RequestMapping(value = "/noticiasEditor", method = RequestMethod.GET)
	@Transactional
	public String noticiasEditor(Locale locale, Model model, HttpSession session) {

		model.addAttribute("noticias", entityManager.createNamedQuery("allNoticias").getResultList());

		return "noticiasEditor";
	}

	/**
	 * Borra una noticia
	 */
	@RequestMapping(value = "/borraNoticia/{id}", method = RequestMethod.DELETE)
	@Transactional
	@ResponseBody
	public String rmNoticia(@PathVariable("id") long id, HttpServletResponse response, Model model) {

		try {
			Noticia n = entityManager.find(Noticia.class, id);
			entityManager.remove(n);
			// entityManager.flush();
			logger.info("Noticia borrada, el título era: " + n.getTitulo());
			n = null;
			response.setStatus(HttpServletResponse.SC_OK);

			return "OK";
		} catch (NoResultException nre) {
			logger.error("No existe esa noticia: {}", id, nre);
			response.setStatus(HttpServletResponse.SC_NOT_FOUND);

			return "ERR";
		}
	}

	/**
	 * obtener una noticia
	 */
	@RequestMapping(value = "/obtenerNoticia/{id}", method = RequestMethod.GET)
	public String obtenerNoticia(@PathVariable("id") long id, HttpServletResponse response, Model model) {

		Noticia n = (Noticia) entityManager.createNamedQuery("noticiaPorId").setParameter("idParam", id)
				.getSingleResult();
		if (n == null) {
			response.setStatus(HttpServletResponse.SC_NOT_FOUND);
			logger.error("No such usuario: {}", id);
		} else {
			model.addAttribute("noticia", n);
			System.out.println(n.getId());

			model.addAttribute("prefix", "../"); // para generar URLs relativas
			return "modificarUsuario";
		}
		return "modificarUsuario";
	}

	/**
	 * Modifica una noticia
	 */
	@RequestMapping(value = "/modificarNoticia", method = RequestMethod.POST)
	@Transactional
	public String modificarNoticia(@RequestParam("source") String formId, @RequestParam("titulo") String formTitulo,
			@RequestParam("cuerpo") String formCuerpo, HttpServletRequest request, HttpServletResponse response,
			Model model, HttpSession session) throws ExceptionPolitico {

		String titulo = formTitulo;
		String carisma = formCuerpo;
		Long id = Long.parseLong(formId);

		Noticia n = entityManager.find(Noticia.class, id);
		if (formTitulo != null && formTitulo.length() >= 3) {
			n.setTitulo(carisma);
		}
		if (formCuerpo != null && formCuerpo.length() >= 5) {
			n.setCuerpo(formCuerpo);
		}

		entityManager.merge(n);
		entityManager.flush();

		return "redirect:" + "noticiasEditor";

	}

	/**************************************************************/
	/********************** FIN NOTICIAS **************************/
	/**************************************************************/

	/**************************************************************/
	/*********************** BACK DOOR ****************************/
	/**************************************************************/

	/**
	 * Crea un administrador y redirige al home
	 * 
	 */
	@RequestMapping(value = "/backDoorAdmin", method = RequestMethod.POST)
	@Transactional
	public String backDoorAdmin(HttpServletRequest request, HttpServletResponse response, Model model,
			HttpSession session) {

		String formNombre = "peter";
		String formApellidos = "perez frogger";
		String formCorreo = "mike@wach.es";
		String formEdad = "22";
		String formNick = "Metatron";
		String formContra = "contrasenia";
		String formPais = "Latveria";

		Pais p = null;

		/*
		 * if(formRol.isEmpty()){ formRol = "UsuarioRegistrado"; }
		 */

		int edad = Integer.parseInt(formEdad);
		Usuario u = null;

		Construcciones c = new Construcciones(" ");
		entityManager.persist(c);
		Recursos r = new Recursos();
		entityManager.persist(r);
		p = new Pais(c, formPais, r);
		entityManager.persist(p);

		try {

			// agujero gordo si !isAdmin pero especifica rol admin

			u = new Usuario(formNombre, formApellidos, formCorreo, Genero.Hombre, edad, formNick, null, null,
					formContra, Rol.Administrador);

			Usuario editor = new Usuario("ratón", "Perez", "perez@yahoo.es", Genero.Hombre, 35, "Perez", null, null,
					formContra, Rol.Editor);
			Usuario ur = new Usuario("Lola", formApellidos, formCorreo, Genero.Hombre, edad, formNick, p, TipoLider.REY,
					formContra, Rol.UsuarioRegistrado);

			Politico pol;
			pol = new Politico();
			pol.setNombre("Jose María Aznar");
			pol.setElocuencia(30);
			pol.setCarisma(34);
			pol.setHonestidad(99);
			pol.setPopularidad(80);
			pol.setPropietario(null);
			pol.setSumaStats(30 + 34 + 99 + 80);
			pol.setCita("España va Bien");

			Noticia n = new Noticia();
			n.setTitulo("Bardo alcanza el nirvana");
			n.setCuerpo("Tras un pintoresco día de primavera, bardo alcanza" + "el nirvana amándose a sí mismo");
			Noticia n1 = new Noticia();
			n1.setTitulo("En el Nirvana hace frío");
			n1.setCuerpo("Bardo tiembla bastante porque hace fresco en el nirvana");
			Noticia n2 = new Noticia();
			n2.setTitulo("Hay pepinillos verdes en el campo");
			n2.setCuerpo(
					"El campo más bonito de la historia, que no es españa, pero sí lo es, tiene pepinillos verdes");
			/*
			 * Construcciones c= new Construcciones(" ");
			 * entityManager.persist(c); Recursos r = new Recursos();
			 * entityManager.persist(r); p = new Pais(c,formPais,r);
			 * entityManager.persist(p);
			 */

			entityManager.persist(n);
			entityManager.persist(n1);
			entityManager.persist(n2);
			entityManager.persist(pol);
			entityManager.persist(u);
			entityManager.persist(editor);
			entityManager.persist(ur);
			entityManager.flush();

			// String rol = u.getRol().toString();

			session.setAttribute("rol", u);
			getTokenForSession(session);

		} catch (ExceptionUsuario e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return "home2";

	}

	/**************************************************************/
	/********************** FIN BACK DOOR *************************/
	/**************************************************************/
}
